# Generated by Django 5.0.7 on 2024-07-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_usuarios',
                'managed': False,
            },
        ),
    ]
