# Generated by Django 5.0.7 on 2024-08-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comunas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id_inmueble', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('m2_construidos', models.FloatField()),
                ('m2_terreno', models.FloatField()),
                ('nro_estacionamiento', models.IntegerField()),
                ('nro_habitaciones', models.IntegerField()),
                ('nro_banio', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('precio_arriendo', models.FloatField()),
            ],
            options={
                'db_table': 'inmuebles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'regiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoInmuble',
            fields=[
                ('id_tipo_inmueble', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_inmueble', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_inmuebles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
